// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FormatXamlExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "FormatXAML2022.31203c8d-aba6-4bd4-8945-96042e76712d";
        public const string Name = "Format XAML 2022";
        public const string Description = @"Format XAML document line by line without encoding to preserve the original string";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Lixfeld";
        public const string Tags = "format, xaml, code formatting, wpf";
    }
}
