// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FormatXamlExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "FormatXamlExtension.31203c8d-aba6-4bd4-8945-96042e76712d";
        public const string Name = "FormatXamlExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
